Repository brown-ccv/ccv-website, pull requests merged in 2020-02, with the labels that each got.

#176 Stronghold Content Update
  .env.example
  content/english/about/_index.md
  content/english/services/consulting/visualization.md
  content/english/services/infrastructure/stronghold.md
  data/info-brown-ccv.json
  data/info-compbiocore.json
  data/opportunities.yaml
  data/people.yaml
  themes/gb-theme/layouts/about/list.html
  themes/gb-theme/static/images/people/JPEG/nate_hover.jpg
  themes/gb-theme/static/images/people/JPEG/nate_main.jpg
  themes/gb-theme/static/images/people/JPEG/yang_hover.jpg
  themes/gb-theme/static/images/people/JPEG/yang_main.jpg
Labels: content, ready

#187 prod: various minor content fixes
  .env.example
  content/english/services/infrastructure/yurt.md
  data/people.yaml
Labels: 2 day wait

#192 Prod: Add Brad, remove hpc posting
  README.md
  data/opportunities.yaml
  data/people.yaml
  index.js
  package-lock.json
  themes/gb-theme/static/images/people/JPEG/bradford_hover.jpg
  themes/gb-theme/static/images/people/JPEG/bradford_main.jpg
Labels: 2 day wait

#196 New search with GCS, mapping bug
  .github/workflows/pr-release-comment.yml
  content/english/documentation/_index.md
  content/english/documentation/jupyterhub-user-manual/_index.md
  content/english/documentation/oscar-user-manual/_index.md
  content/english/documentation/stronghold/_index.md
  content/english/services/consulting/workshops.md
  index.js
  themes/gb-theme/assets/js/custom.js
  themes/gb-theme/assets/js/globus-auth.js
  themes/gb-theme/assets/js/google-sign-in.js
  themes/gb-theme/assets/styles/custom/components/_search.scss
  themes/gb-theme/assets/styles/custom/custom.scss
  themes/gb-theme/layouts/partials/blocks/quick_links.html
  themes/gb-theme/layouts/partials/footer/scripts.html
  themes/gb-theme/layouts/partials/header/site-nav.html
Labels: 4 day wait

#199 ci: move labeling to master PRs, update readme
  .github/workflows/pr-release-comment.yml
  .github/workflows/prcomment.yml
  README.md
Labels: ready

#202 Misc Issues
  README.md
  config.yml
  content/english/hidden/how-to-write-md.md
  content/english/hidden/signatures.md
  content/english/services/infrastructure/cave.md
  data/._rates.yaml
  data/people.yaml
  themes/gb-theme/layouts/_default/single.html
  themes/gb-theme/layouts/about/list.html
  themes/gb-theme/layouts/partials/blocks/quick_links.html
  themes/gb-theme/layouts/partials/footer/site-footer.html
  themes/gb-theme/layouts/shortcodes/email_signature.html
  themes/gb-theme/static/.DS_Store
  themes/gb-theme/static/images/.DS_Store
  themes/gb-theme/static/images/background-image.svg
  themes/gb-theme/static/images/background.svg
  themes/gb-theme/static/images/bigdatablog.jpg
  themes/gb-theme/static/images/ccv-logo-144ppi.png
  themes/gb-theme/static/images/ccvcon-banner-web.png
  themes/gb-theme/static/images/ccvcon.gif
  themes/gb-theme/static/images/github-brands.png
  themes/gb-theme/static/images/info-circle-solid.png
  themes/gb-theme/static/images/people/JPEG/bell_hover.jpg
  themes/gb-theme/static/images/people/JPEG/bell_main.jpg
  themes/gb-theme/static/images/people/JPEG/kalvin_hover.jpg
  themes/gb-theme/static/images/people/JPEG/kalvin_main.jpg
  themes/gb-theme/static/images/people/JPEG/max_hover.jpg
  themes/gb-theme/static/images/people/JPEG/max_main.jpg
  themes/gb-theme/static/images/people/JPEG/raj_hover.jpg
  themes/gb-theme/static/images/people/JPEG/raj_main.jpg
Labels: ready

#205 fix: 🐛 fix markdown in about
  content/english/about/_index.md
Labels: ready
