Repository brown-ccv/ccv-website, pull requests merged in 2020-03, with the labels that each got.

#207 feat: separate facilities section
  config.yml
  content/english/about/_index.md
  content/english/facilities/_index.md
  themes/gb-theme/i18n/en.yaml
  themes/gb-theme/layouts/facilities/list.html
Labels: ready

#210 feat: 🎸 add covid statement
  config.yml
  themes/gb-theme/layouts/index.html
  themes/gb-theme/layouts/partials/blocks/covid.html
Labels: 4 day wait

#208 change condo cores from 256 to 512
  content/english/services/rates.md
Labels: ready

#215 feat: 🎸 update yurt open hours statement
  content/english/services/infrastructure/yurt.md
Labels: 2 day wait

#214 replace old form link with new one
  content/english/_index.md
  content/english/services/infrastructure/oscar.md
Labels: 2 day wait

#212 feat: 🎸 move rates table to shortcut and convert to HTML
  content/english/services/rates.md
  themes/gb-theme/layouts/_default/single.html
  themes/gb-theme/layouts/shortcodes/rates.html
Labels: 4 day wait

#216 Feat rates table
  content/english/services/rates.md
  themes/gb-theme/layouts/shortcodes/rates.html
Labels: 2 day wait

#219 fix: 🐛 fix rate table bullet points
  content/english/services/rates.md
Labels: 2 day wait

#222 fix: 🐛 fix buttons jh
  content/english/services/consulting/jupyterhub.md
  themes/gb-theme/layouts/shortcodes/flexrow.html
Labels: ready

#223 update facilities statement
  content/english/facilities/_index.md
Labels: 2 day wait

#225 Fix multiple issues
  content/english/services/infrastructure/terms-and-conditions.md
  data/people.yaml
  themes/gb-theme/static/images/people/JPEG/kirk_hover.jpg
  themes/gb-theme/static/images/people/JPEG/kirk_main.jpg
  themes/gb-theme/static/images/people/JPEG/kuba_hover.jpg
  themes/gb-theme/static/images/people/JPEG/kuba_main.jpg
Labels: ready
