Repository brown-ccv/ccv-website, pull requests merged in 2020-05, with the labels that each got.

#247 feat: 🎸 add calendar
  themes/gb-theme/layouts/partials/blocks/events.html
Labels: ready

#257 fix: 🐛 fix xsede text
  content/english/services/infrastructure/xsede.md
Labels: ready

#250 Add Globus Service Content
  content/english/services/infrastructure/globus.md
Labels: 2 day wait, ready

#255 refactor: 💡 change vm request link from email to ccv to form
  content/english/services/infrastructure/virtual-machines.md
Labels: 2 day wait, ready

#259 update storage rates
  content/english/services/rates.md
Labels: 2 day wait

#263 fix: fixes broken markdown on storage table
  content/english/services/infrastructure/storage.md
Labels: ready

#266 Adding Rohit to People page
  data/people.yaml
  themes/gb-theme/static/images/people/JPEG/rohit_hover.jpg
  themes/gb-theme/static/images/people/JPEG/rohit_main.jpg
Labels: ready

#268 Feat interns
  content/english/.DS_Store
  data/interns2020.yaml
  themes/gb-theme/assets/js/custom.js
  themes/gb-theme/assets/styles/custom/components/_confetti.scss
  themes/gb-theme/assets/styles/custom/custom.scss
  themes/gb-theme/layouts/index.html
  themes/gb-theme/layouts/partials/blocks/events.html
  themes/gb-theme/layouts/partials/blocks/interns.html
  themes/gb-theme/layouts/partials/blocks/quick_links.html
  themes/gb-theme/layouts/partials/blocks/whatsnew.html
  themes/gb-theme/layouts/partials/footer/scripts.html
Labels: 4 day wait

#270 add link to system overview in docs
  content/english/facilities/_index.md
Labels: 2 day wait
