Repository brown-ccv/ccv-website, pull requests merged in 2020-04, with the labels that each got.

#228 refactor: add covid condo notice
  config.yml
  themes/gb-theme/layouts/partials/blocks/covid.html
Labels: high-priority

#233 fix: 🐛 remove positions
  data/opportunities.yaml
  themes/gb-theme/layouts/about/list.html
Labels: ready

#232 feat: dedicated covid page
  config.yml
  content/english/covid/_index.md
  data/whatsnew.yaml
  themes/gb-theme/assets/styles/custom/components/_covid.scss
  themes/gb-theme/assets/styles/custom/custom.scss
  themes/gb-theme/layouts/_default/list.html
  themes/gb-theme/layouts/about/list.html
  themes/gb-theme/layouts/covid/list.html
  themes/gb-theme/layouts/index.html
  themes/gb-theme/layouts/partials/blocks/covid.html
  themes/gb-theme/layouts/partials/head/prerender.html
  themes/gb-theme/layouts/partials/header/site-nav.html
Labels: ready

#235 fix: add trailing / to relative links
  data/whatsnew.yaml
  themes/gb-theme/layouts/partials/blocks/covid.html
Labels: ready

#227 fix: 🐛 change google search code
  themes/gb-theme/assets/js/custom.js
  themes/gb-theme/layouts/partials/footer/scripts.html
Labels: ready

#237 fix: fix typos in yurt and cave descriptions
  content/english/services/infrastructure/cave.md
  content/english/services/infrastructure/yurt.md
Labels: ready

#241 fix: fix description of hpc resource eligibility
  content/english/covid/_index.md
  themes/gb-theme/layouts/covid/list.html
Labels: ready

#244 fix: 🐛 fix discourse button
  content/english/services/consulting/discourse.md
Labels: ready

#246 feat(documentation): Add new link to Globus docs
  data/documentation.yaml
Labels: ready

#221 feat: 🎸 reorg consulting section, add getting help section, add xsede
  config.yml
  content/english/services/consulting/advanced-research-computing.md
  content/english/services/consulting/deskpro.md
  content/english/services/consulting/discourse.md
  content/english/services/consulting/hpc-xsede.md
  content/english/services/consulting/office_hours.md
  content/english/services/consulting/slack.md
  content/english/services/consulting/visualization.md
  content/english/services/infrastructure/xsede.md
  themes/gb-theme/layouts/_default/list.html
  themes/gb-theme/layouts/_default/single.html
  themes/gb-theme/layouts/partials/footer/site-footer.html
  themes/gb-theme/layouts/shortcodes/tile.html
Labels: 4 day wait, ready
