Repository brown-ccv/ccv-website, pull requests merged in 2021-02, with the labels that each got.

#353 fix: update ashok title
  data/people.yaml
Labels: ready

#356 fix: switch jordan and joselynn
  data/people.yaml
Labels: ready

#357 Content add intern photo
  data/people.yaml
  package-lock.json
  themes/gb-theme/static/images/people/JPEG/galen_hover.jpg
  themes/gb-theme/static/images/people/JPEG/galen_main.jpg
Labels: 2.5 day wait

#359 feat: add link to status page in quick links
  content/english/_index.md
  package-lock.json
  themes/gb-theme/assets/styles/custom/components/_layout.scss
  themes/gb-theme/static/images/people/JPEG/.DS_Store
Labels: 2.5 day wait

#360 feat: 🎸 Updating Facilities Statement
  content/english/facilities/_index.md
Labels: 1 day wait

#364 feat: 🎸 Updating Oscar Specs
  content/english/services/infrastructure/oscar.md
Labels: 2.5 day wait

#363 feat: 🎸 add two open positions and whatsnew card
  data/opportunities.yaml
  data/whatsnew.yaml
  package-lock.json
Labels: ready

#365 feat: 🎸 Changing Rates Column
  themes/gb-theme/layouts/shortcodes/rates.html
Labels: 2.5 day wait

#369 feat: 🎸 add nando to about page
  data/people.yaml
  themes/gb-theme/static/images/people/JPEG/nando_hover.jpg
  themes/gb-theme/static/images/people/JPEG/nando_main.jpg
Labels: ready

#371 data: remove ben
  data/people.yaml
  themes/gb-theme/static/images/people/JPEG/ben_hover.jpg
  themes/gb-theme/static/images/people/JPEG/ben_main.jpg
Labels: ready

#372 data: fix singh title
  data/people.yaml
Labels: ready
