Repository brown-ccv/ccv-website, pull requests merged in 2025-09, with the labels that each got.

#295 fix: button inconsistencies and sizing
  .gitignore
  app/about/careers/page.tsx
  app/not-found.tsx
  app/page.tsx
  app/services/ai-tools/page.tsx
  app/services/project-consulting/page.tsx
  app/services/storage/compare/page.tsx
  app/services/storage/page.tsx
  components/BrownBanner.tsx
  components/EventSection.tsx
  components/FeaturedCarousel.tsx
  components/Footer.tsx
  components/Workday.tsx
  components/button/variants.tsx
  components/storage/StorageTable.tsx
  components/storage/StorageTool.tsx
  content/about/contact.mdx
  content/images/people/sam_hover.jpeg
  content/images/people/sam_hover.png
  mdx-components.tsx
  package-lock.json
  package.json
Labels: bug

#297 Chore: Clean contact us links
  app/page.tsx
  components/BrownBanner.tsx
  components/CopyableEmail.tsx
  components/Footer.tsx
  content/about/contact.mdx
  content/about/contact.yaml
  content/services/classroom.mdx
  content/services/project-consulting.mdx
  mdx-components.tsx
Labels: enhancement

#304 style: padding/margin between ccvbars and h2
  app/globals.css
  components/LocationSection.tsx
  components/SectionHeader.tsx
  components/card/HeroCard.tsx
Labels: bug

#316 fix: attribution links for images in carousel
  components/FeaturedCarousel.tsx
  content/services/classroom-carousel.yaml
Labels: enhancement

#317 fix: workday text size and query
  app/about/careers/page.tsx
  app/about/queries.js
  components/Workday.tsx
  components/card/OpportunitiesCard.tsx
Labels: bug

#319 fix: styledtab erroneously shows up on mobile view
  components/EventSection.tsx
Labels: bug

#318 Refactor: inconsistent buttons
  app/about/careers/page.tsx
  components/Navbar.tsx
  components/storage/StorageTool.tsx
Labels: refactor

#339 fix: navbar highlight on submenu open
  components/Navbar.tsx
Labels: bug
